# Generated by Django 6.0 on 2025-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/experiences/')),
                ('paragraph', models.TextField(help_text='Short narrative paragraph')),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('context', models.CharField(blank=True, help_text="Optional context (e.g., 'Weekend workshop attendee')", max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Experience',
                'verbose_name_plural': 'Customer Experiences',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/gallery/')),
                ('category', models.CharField(choices=[('product', 'Product Gallery'), ('workshop', 'Workshop Moments'), ('studio', 'Studio & Events')], max_length=20)),
                ('caption', models.CharField(blank=True, help_text='Admin-only caption', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('quote', models.TextField(help_text='The testimonial text')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Text Testimonial',
                'verbose_name_plural': 'Text Testimonials',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(help_text='Short description of the video', max_length=300)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='media/videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo embed URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnails/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Testimonial',
                'verbose_name_plural': 'Video Testimonials',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
