# Generated by Django 6.0 on 2026-01-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerexperience',
            name='title',
            field=models.CharField(default='Experience Title', help_text='Experience title/heading', max_length=200),
            preserve_default=False,
        ),
    ]
