# Generated by Django 6.0 on 2026-01-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0002_customerexperience_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerexperience',
            name='image',
            field=models.ImageField(upload_to='experiences/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='videotestimonial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videotestimonial',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
