# Generated by Django 6.0 on 2026-01-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0003_alter_customerexperience_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerexperience',
            name='image',
            field=models.ImageField(upload_to='media/experiences/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='media/gallery/'),
        ),
        migrations.AlterField(
            model_name='videotestimonial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videotestimonial',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/'),
        ),
    ]
