# Generated by Django 6.0 on 2025-12-24 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('workshop_type', models.CharField(choices=[('group', 'Group Workshop'), ('one-on-one', 'One-on-One Workshop'), ('couple', 'Couple Pottery Date'), ('birthday', 'Birthday Celebration'), ('party', 'Farm & Garden Mini Party')], max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='all', max_length=20)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('min_age', models.IntegerField(default=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshops/')),
                ('is_active', models.BooleanField(default=True)),
                ('available_slots', models.IntegerField(default=0)),
                ('includes_materials', models.BooleanField(default=True)),
                ('includes_refreshments', models.BooleanField(default=False)),
                ('takes_home_creation', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-is_popular', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_spots', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='workshops.workshop')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('workshop', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('number_of_participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('special_requests', models.TextField(blank=True)),
                ('experience_level', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshops.workshop')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshops.workshopslot')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
