# Generated by Django 6.0 on 2025-12-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: external image URL'),
        ),
    ]
