# Generated by Django 6.0 on 2025-12-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='registration_number',
            field=models.CharField(default='WS-TEMP', editable=False, max_length=50, unique=True),
        ),
    ]
