# Generated by Django 6.0 on 2025-12-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_alter_workshopregistration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopregistration',
            options={'ordering': ['-registered_at'], 'verbose_name': 'Workshop Registration', 'verbose_name_plural': 'Purchases - Workshop Registrations'},
        ),
    ]
