# Generated by Django 6.0 on 2025-12-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_alter_workshopregistration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopregistration',
            options={'ordering': ['-registered_at'], 'verbose_name': 'Workshop Registration', 'verbose_name_plural': 'Workshops - Registrations (Purchases)'},
        ),
    ]
