# Generated by Django 6.0 on 2026-01-03 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_alter_workshopregistration_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked user if logged in during registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
