# Generated by Django 6.0 on 2026-01-18 12:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_workshopregistration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
