# Generated by Django 6.0 on 2026-01-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioTourSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload 360 tour image here', upload_to='studio/360-tour/')),
                ('active', models.BooleanField(default=True, help_text='If unchecked, component might use default or hide')),
            ],
            options={
                'verbose_name': 'Studio Tour Settings',
                'verbose_name_plural': 'Studio Tour Settings',
            },
        ),
    ]
