# Generated by Django 6.0 on 2026-01-18 12:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_studiotoursettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgalleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='pastpopup',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='studiotoursettings',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Upload 360 tour image here', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='upcomingexhibition',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
