# Generated by Django 6.0 on 2026-01-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a high-quality image for the gallery', upload_to='creations/')),
                ('url', models.URLField(blank=True, help_text='Link to product page or event (optional)', null=True)),
                ('height', models.IntegerField(default=300, help_text='Height in pixels for masonry layout (e.g., 200, 300, 400)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('alt_text', models.CharField(blank=True, default='Basho Creation', help_text='Alt text for accessibility', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Creation',
                'verbose_name_plural': 'Creations Gallery',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
