# Generated by Django 6.0 on 2025-12-23 17:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('project_type', models.CharField(choices=[('tableware', 'Tableware Set'), ('art', 'Art Piece'), ('corporate', 'Corporate Order'), ('event', 'Event/Wedding'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text="Customer's vision/requirements")),
                ('budget', models.CharField(blank=True, choices=[('5000-10000', '₹5,000 - ₹10,000'), ('10000-25000', '₹10,000 - ₹25,000'), ('25000-50000', '₹25,000 - ₹50,000'), ('50000+', '₹50,000+')], max_length=20)),
                ('gst_number', models.CharField(blank=True, help_text='For invoice generation', max_length=15)),
                ('reference_images', models.ImageField(blank=True, null=True, upload_to='custom_orders/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('contacted', 'Customer Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Order',
                'verbose_name_plural': 'Custom Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text="Unique identifier (e.g., 'bowl-1')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Product name (e.g., 'Zen Breakfast Bowl')", max_length=200)),
                ('category', models.CharField(choices=[('tableware', 'Tableware'), ('art', 'Art Pieces'), ('custom', 'Custom Order')], default='tableware', max_length=20)),
                ('description', models.TextField(help_text='Product description')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for cards', max_length=300)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (used for shipping calculation)', max_digits=5, null=True)),
                ('dimensions', models.CharField(blank=True, help_text="e.g., '10 inches diameter'", max_length=100)),
                ('is_food_safe', models.BooleanField(default=True)),
                ('is_microwave_safe', models.BooleanField(default=True)),
                ('is_dishwasher_safe', models.BooleanField(default=True)),
                ('is_handmade', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_bestseller', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative: external image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='For guest users', max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
