# Generated by Django 6.0 on 2025-12-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Order', 'verbose_name_plural': 'Purchases - Product Orders'},
        ),
    ]
