# Generated by Django 6.0 on 2026-01-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_order_user_profile_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='How to care for and maintain the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text="Material used (e.g., 'Stoneware clay with natural glaze')", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(blank=True, help_text='How to use the product'),
        ),
    ]
