# Generated by Django 6.0 on 2026-01-09 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_care_instructions_product_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_kg', models.DecimalField(decimal_places=2, default=50.0, help_text='Shipping cost per kilogram (₹)', max_digits=8)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum shipping charge regardless of weight (₹)', max_digits=8)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=5000.0, help_text='Free shipping for orders above this amount (₹). Set to 0 to disable.', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last updated by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Configuration',
                'verbose_name_plural': 'Shipping Configuration',
            },
        ),
    ]
