# Generated by Django 6.0 on 2026-01-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_shippingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(choices=[('gifting', 'Corporate Gifting'), ('workshop', 'Team Workshop'), ('collaboration', 'Brand Collaboration'), ('other', 'Other')], max_length=20)),
                ('team_size', models.CharField(blank=True, help_text='Number of participants or recipients', max_length=100)),
                ('budget_range', models.CharField(blank=True, help_text='Estimated budget', max_length=100)),
                ('message', models.TextField(help_text='Detailed inquiry message')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Customer Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='new', max_length=20)),
                ('inquiry_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Staff notes (not visible to customer)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corporate Inquiry',
                'verbose_name_plural': 'Corporate Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
