# Generated by Django 6.0 on 2026-01-18 12:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_corporateinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='reference_images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Product image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
